version: "2"
services:
  app:
    container_name: app
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "5858:5858"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"